#                             Aggregation operations (sum, min, max, etc)


Apart from element-wise operations, NumPy also includes a host of aggregation operations like sum, min, max, mean, etc.

All of these functions are available directly in the NumPy import, as in np.sum(b), np.min(b), etc. And most of the functions are
also available as methods of the array class. Hence, we can also do b.sum(), b.min(), etc.

Lastly, aggregation operations can work over all elements of the array, or over specific dimensions. For example, we can use 
axis=0 to perform an operation for each column.

In [1]:
import numpy as np

In [10]:
b= np.array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [11]:
c=b+5
c

array([[12,  5,  6,  5,  7,  8],
       [ 6,  8,  5,  6,  7,  5],
       [ 5,  6,  5,  5,  6,  8]])

In [12]:
# sum of all elements

b.sum()

25

In [13]:
# sum of each column
b.sum(axis=0)

array([8, 4, 1, 1, 5, 6])

In [14]:
# sum of each row
b.sum(axis=1)

array([13,  7,  5])

Similarly, we have functions like min (minimum), max (maximum), cumsum (cumulative summation).

In [15]:
b.min()

0

In [16]:
# min element each row
b.min(axis=1)

array([0, 0, 0])

In [17]:
#min value in each column
b.min(axis=0)

array([0, 0, 0, 0, 1, 0])

In [18]:
b.max()

7

In [20]:
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [19]:
b.cumsum()

array([ 7,  7,  8,  8, 10, 13, 14, 17, 17, 18, 20, 20, 20, 21, 21, 21, 22,
       25], dtype=int32)

In [21]:
b.cumsum(axis=1)

array([[ 7,  7,  8,  8, 10, 13],
       [ 1,  4,  4,  5,  7,  7],
       [ 0,  1,  1,  1,  2,  5]], dtype=int32)

In [22]:
b.cumsum(axis=0)

array([[7, 0, 1, 0, 2, 3],
       [8, 3, 1, 1, 4, 3],
       [8, 4, 1, 1, 5, 6]], dtype=int32)

mean, median, std (standard deviation).

In [23]:
b.mean()

1.3888888888888888

In [24]:
b.mean(axis=0)

array([2.66666667, 1.33333333, 0.33333333, 0.33333333, 1.66666667,
       2.        ])

In [25]:
np.median(b)

1.0

In [28]:
np.median(b,axis=1)

array([1.5, 1. , 0.5])

In [29]:
np.std(b,axis=0)

array([3.09120617, 1.24721913, 0.47140452, 0.47140452, 0.47140452,
       1.41421356])

In [30]:
# We can also find mean by np.mean
np.mean(b,axis=0)

array([2.66666667, 1.33333333, 0.33333333, 0.33333333, 1.66666667,
       2.        ])

In [31]:
# we can also find unique values in array
np.unique(b)

array([0, 1, 2, 3, 7])

# Matrix Oparations

Matrix Operations (dot products, matrix multiplication, etc)
Now, lets look at some matrix operations that NumPy supports. np.dot(x, y) can be used to perform both dot-products as well as 
matrix multiplication

In [32]:
v=b[:,0]
v

array([7, 1, 0])

In [34]:
w=b[:,1]
w

array([0, 3, 1])

In [35]:
# Dot Product  (7*0+1*3+0*1)
v.dot(w)

3

In [36]:
np.dot(v,w)

3

In [37]:
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [38]:
b.T

array([[7, 1, 0],
       [0, 3, 1],
       [1, 0, 0],
       [0, 1, 0],
       [2, 2, 1],
       [3, 0, 3]])

In [39]:
# Matrix vector product result will change as we change the order
b.dot(b.T)

array([[63, 11, 11],
       [11, 15,  5],
       [11,  5, 11]])

In [40]:
b.T.dot(b)

array([[50,  3,  7,  1, 16, 21],
       [ 3, 10,  0,  3,  7,  3],
       [ 7,  0,  1,  0,  2,  3],
       [ 1,  3,  0,  1,  2,  0],
       [16,  7,  2,  2,  9,  9],
       [21,  3,  3,  0,  9, 18]])

Conclusion
In summary, advantages of using NumPy

array oriented computing
efficiently implemented multi-dimensional arrays
designed for scientific computation
sophisticated functions for initializing, slicing and manipulating arrays (and shaping, stacking, splitting).
performing vector and matrix operations like sum, cumulative sum, mean, normalization, matrix multiplication, etc.
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data 
(including strings and objects). 