In [6]:
import numpy as np

In [7]:
a= np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
b= np.array([[7, 1, 0],
       [0, 3, 1],
       [1, 0, 0],
       [0, 1, 0],
       [2, 2, 1],
       [3, 0, 3]])

In [9]:
# Transpose of the ndarray
b.transpose()

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [10]:
# Reshaping ndarray
# You should consider size of orginal array and the one you are reshaping must be same.

a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# Resize
# Rearrange does not need to have same size as the size of original array
# syntax np.resize(array,(size))
np.resize(a,(4,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# Broadcast_to
# make sure you must have same column as the orginal array
np.broadcast_to(a,(6,8))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [13]:
# ndarray while broadcasting make sure rows as well as column should be in same order 
# e.g in below example 6x3 
np.broadcast_to(b,(2,6,3))

array([[[7, 1, 0],
        [0, 3, 1],
        [1, 0, 0],
        [0, 1, 0],
        [2, 2, 1],
        [3, 0, 3]],

       [[7, 1, 0],
        [0, 3, 1],
        [1, 0, 0],
        [0, 1, 0],
        [2, 2, 1],
        [3, 0, 3]]])

Expanding and squeezing dimensions
expand_dims and squeeze can be used to add or remove dimensions from an array.

In [14]:
b=b.transpose()
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [15]:
# Expand the shape of an array by inserting axis 
np.expand_dims(b,axis=1)

array([[[7, 0, 1, 0, 2, 3]],

       [[1, 3, 0, 1, 2, 0]],

       [[0, 1, 0, 0, 1, 3]]])

In [16]:
np.squeeze(b)

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

Concatenating and stacking
concatenate and stack can be used to join multiple arrays into one. concatenate joins arrays along an existing axis, thereby, 
the total number of dimensions stays the same. stack on the other hand, creates a new dimension. The arrays must have the same shape.

In [17]:
c= b+5
c

array([[12,  5,  6,  5,  7,  8],
       [ 6,  8,  5,  6,  7,  5],
       [ 5,  6,  5,  5,  6,  8]])

In [18]:
# Vertical concatenation
np.concatenate((b,c),axis=0)

array([[ 7,  0,  1,  0,  2,  3],
       [ 1,  3,  0,  1,  2,  0],
       [ 0,  1,  0,  0,  1,  3],
       [12,  5,  6,  5,  7,  8],
       [ 6,  8,  5,  6,  7,  5],
       [ 5,  6,  5,  5,  6,  8]])

In [19]:
# Horizontal Concatenation
np.concatenate((b,c),axis=1)

array([[ 7,  0,  1,  0,  2,  3, 12,  5,  6,  5,  7,  8],
       [ 1,  3,  0,  1,  2,  0,  6,  8,  5,  6,  7,  5],
       [ 0,  1,  0,  0,  1,  3,  5,  6,  5,  5,  6,  8]])

In [20]:
#Join arrays along a new axis, 0
np.stack((b,c),axis=0)

array([[[ 7,  0,  1,  0,  2,  3],
        [ 1,  3,  0,  1,  2,  0],
        [ 0,  1,  0,  0,  1,  3]],

       [[12,  5,  6,  5,  7,  8],
        [ 6,  8,  5,  6,  7,  5],
        [ 5,  6,  5,  5,  6,  8]]])

In [21]:
np.stack((b,c),axis=1)

array([[[ 7,  0,  1,  0,  2,  3],
        [12,  5,  6,  5,  7,  8]],

       [[ 1,  3,  0,  1,  2,  0],
        [ 6,  8,  5,  6,  7,  5]],

       [[ 0,  1,  0,  0,  1,  3],
        [ 5,  6,  5,  5,  6,  8]]])

Splitting
split, hsplit (horizontal split) and vsplit (vertical split) can be used to split an array into equal-sized subarrays.

In [22]:
np.split(b,3)

[array([[7, 0, 1, 0, 2, 3]]),
 array([[1, 3, 0, 1, 2, 0]]),
 array([[0, 1, 0, 0, 1, 3]])]

In [23]:
np.split(c,3)

[array([[12,  5,  6,  5,  7,  8]]),
 array([[6, 8, 5, 6, 7, 5]]),
 array([[5, 6, 5, 5, 6, 8]])]

In [24]:
np.split(c,3,axis=1)

[array([[12,  5],
        [ 6,  8],
        [ 5,  6]]), array([[6, 5],
        [5, 6],
        [5, 5]]), array([[7, 8],
        [7, 5],
        [6, 8]])]

In [25]:
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [26]:
np.hsplit(b,3)

[array([[7, 0],
        [1, 3],
        [0, 1]]), array([[1, 0],
        [0, 1],
        [0, 0]]), array([[2, 3],
        [2, 0],
        [1, 3]])]

    #Append, insert and delete
And finally, append, insert and delete can be used to insert and delete elements from an array (the same way as in Python). 
append is equivalent to inserting elements to the end of the array.

In [27]:
# append will always apend elements at the end
a=np.append(a,[11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12])

In [31]:
# If you want to insert element in between array we have to  use insert

np.insert(a,3,[0,0])

array([ 1,  2,  3,  0,  0,  4,  5,  6,  7,  8, 11, 12])

In [33]:
# Delete perticular set of elements
np.delete(a,[1,3])

array([ 1,  3,  5,  6,  7,  8, 11, 12])

In [34]:
np.delete(a,[6])

array([ 1,  2,  3,  4,  5,  6,  8, 11, 12])

In [36]:
b

array([[7, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

In [37]:
c

array([[12,  5,  6,  5,  7,  8],
       [ 6,  8,  5,  6,  7,  5],
       [ 5,  6,  5,  5,  6,  8]])

In [35]:
# Element wise operation
b+c
# also can use method np.add(b,c)

array([[19,  5,  7,  5,  9, 11],
       [ 7, 11,  5,  7,  9,  5],
       [ 5,  7,  5,  5,  7, 11]])

In [39]:
np.add(b,c)

array([[19,  5,  7,  5,  9, 11],
       [ 7, 11,  5,  7,  9,  5],
       [ 5,  7,  5,  5,  7, 11]])

In [38]:
# element wise substraction

c-b

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [40]:
np.subtract(c,b)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [41]:
b*c

array([[84,  0,  6,  0, 14, 24],
       [ 6, 24,  0,  6, 14,  0],
       [ 0,  6,  0,  0,  6, 24]])

In [42]:
np.multiply(b,c)

array([[84,  0,  6,  0, 14, 24],
       [ 6, 24,  0,  6, 14,  0],
       [ 0,  6,  0,  0,  6, 24]])

In [44]:
b/c

array([[0.58333333, 0.        , 0.16666667, 0.        , 0.28571429,
        0.375     ],
       [0.16666667, 0.375     , 0.        , 0.16666667, 0.28571429,
        0.        ],
       [0.        , 0.16666667, 0.        , 0.        , 0.16666667,
        0.375     ]])

In [45]:
np.divide(b,c)

array([[0.58333333, 0.        , 0.16666667, 0.        , 0.28571429,
        0.375     ],
       [0.16666667, 0.375     , 0.        , 0.16666667, 0.28571429,
        0.        ],
       [0.        , 0.16666667, 0.        , 0.        , 0.16666667,
        0.375     ]])

NumPy also includes a number of element-wise operations, such as sqrt (square-root) and log (logarithm).

In [46]:
np.sqrt(b)

array([[2.64575131, 0.        , 1.        , 0.        , 1.41421356,
        1.73205081],
       [1.        , 1.73205081, 0.        , 1.        , 1.41421356,
        0.        ],
       [0.        , 1.        , 0.        , 0.        , 1.        ,
        1.73205081]])